// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/orderbookl2_v1/request.proto

#include "sdk/stream/orderbookl2_v1/request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
PROTOBUF_CONSTEXPR StreamOrderBookL2RequestV1::StreamOrderBookL2RequestV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrument_criteria_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamOrderBookL2RequestV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamOrderBookL2RequestV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamOrderBookL2RequestV1DefaultTypeInternal() {}
  union {
    StreamOrderBookL2RequestV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamOrderBookL2RequestV1DefaultTypeInternal _StreamOrderBookL2RequestV1_default_instance_;
PROTOBUF_CONSTEXPR StreamOrderBookL2ReplayRequestV1::StreamOrderBookL2ReplayRequestV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.instrument_criteria_)*/nullptr
  , /*decltype(_impl_.interval_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamOrderBookL2ReplayRequestV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamOrderBookL2ReplayRequestV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamOrderBookL2ReplayRequestV1DefaultTypeInternal() {}
  union {
    StreamOrderBookL2ReplayRequestV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamOrderBookL2ReplayRequestV1DefaultTypeInternal _StreamOrderBookL2ReplayRequestV1_default_instance_;
}  // namespace kaikosdk
static ::_pb::Metadata file_level_metadata_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamOrderBookL2RequestV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamOrderBookL2RequestV1, _impl_.instrument_criteria_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamOrderBookL2ReplayRequestV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamOrderBookL2ReplayRequestV1, _impl_.instrument_criteria_),
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamOrderBookL2ReplayRequestV1, _impl_.interval_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamOrderBookL2RequestV1)},
  { 7, -1, -1, sizeof(::kaikosdk::StreamOrderBookL2ReplayRequestV1)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::kaikosdk::_StreamOrderBookL2RequestV1_default_instance_._instance,
  &::kaikosdk::_StreamOrderBookL2ReplayRequestV1_default_instance_._instance,
};

const char descriptor_table_protodef_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\'sdk/stream/orderbookl2_v1/request.prot"
  "o\022\010kaikosdk\032\034sdk/core/data_interval.prot"
  "o\032\"sdk/core/instrument_criteria.proto\"W\n"
  "\032StreamOrderBookL2RequestV1\0229\n\023instrumen"
  "t_criteria\030\001 \001(\0132\034.kaikosdk.InstrumentCr"
  "iteria\"\207\001\n StreamOrderBookL2ReplayReques"
  "tV1\0229\n\023instrument_criteria\030\001 \001(\0132\034.kaiko"
  "sdk.InstrumentCriteria\022(\n\010interval\030\002 \001(\013"
  "2\026.kaikosdk.DataIntervalB\215\001\n#com.kaiko.s"
  "dk.stream.orderbookl2_v1P\001ZFgithub.com/k"
  "aikodata/kaiko-go-sdk/stream/orderbookl2"
  "_v1;orderbookl2_v1\252\002\033KaikoSdk.Stream.Ord"
  "erBookL2b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_deps[2] = {
  &::descriptor_table_sdk_2fcore_2fdata_5finterval_2eproto,
  &::descriptor_table_sdk_2fcore_2finstrument_5fcriteria_2eproto,
};
static ::_pbi::once_flag descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto = {
    false, false, 496, descriptor_table_protodef_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto,
    "sdk/stream/orderbookl2_v1/request.proto",
    &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_once, descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_deps, 2, 2,
    schemas, file_default_instances, TableStruct_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto::offsets,
    file_level_metadata_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto, file_level_enum_descriptors_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto,
    file_level_service_descriptors_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto(&descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto);
namespace kaikosdk {

// ===================================================================

class StreamOrderBookL2RequestV1::_Internal {
 public:
  static const ::kaikosdk::InstrumentCriteria& instrument_criteria(const StreamOrderBookL2RequestV1* msg);
};

const ::kaikosdk::InstrumentCriteria&
StreamOrderBookL2RequestV1::_Internal::instrument_criteria(const StreamOrderBookL2RequestV1* msg) {
  return *msg->_impl_.instrument_criteria_;
}
void StreamOrderBookL2RequestV1::clear_instrument_criteria() {
  if (GetArenaForAllocation() == nullptr && _impl_.instrument_criteria_ != nullptr) {
    delete _impl_.instrument_criteria_;
  }
  _impl_.instrument_criteria_ = nullptr;
}
StreamOrderBookL2RequestV1::StreamOrderBookL2RequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamOrderBookL2RequestV1)
}
StreamOrderBookL2RequestV1::StreamOrderBookL2RequestV1(const StreamOrderBookL2RequestV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamOrderBookL2RequestV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_criteria_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_instrument_criteria()) {
    _this->_impl_.instrument_criteria_ = new ::kaikosdk::InstrumentCriteria(*from._impl_.instrument_criteria_);
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamOrderBookL2RequestV1)
}

inline void StreamOrderBookL2RequestV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_criteria_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StreamOrderBookL2RequestV1::~StreamOrderBookL2RequestV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamOrderBookL2RequestV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamOrderBookL2RequestV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.instrument_criteria_;
}

void StreamOrderBookL2RequestV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamOrderBookL2RequestV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamOrderBookL2RequestV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.instrument_criteria_ != nullptr) {
    delete _impl_.instrument_criteria_;
  }
  _impl_.instrument_criteria_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamOrderBookL2RequestV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_instrument_criteria(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamOrderBookL2RequestV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamOrderBookL2RequestV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::instrument_criteria(this),
        _Internal::instrument_criteria(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamOrderBookL2RequestV1)
  return target;
}

size_t StreamOrderBookL2RequestV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamOrderBookL2RequestV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.instrument_criteria_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamOrderBookL2RequestV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamOrderBookL2RequestV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamOrderBookL2RequestV1::GetClassData() const { return &_class_data_; }


void StreamOrderBookL2RequestV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamOrderBookL2RequestV1*>(&to_msg);
  auto& from = static_cast<const StreamOrderBookL2RequestV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamOrderBookL2RequestV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_instrument_criteria()) {
    _this->_internal_mutable_instrument_criteria()->::kaikosdk::InstrumentCriteria::MergeFrom(
        from._internal_instrument_criteria());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamOrderBookL2RequestV1::CopyFrom(const StreamOrderBookL2RequestV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamOrderBookL2RequestV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamOrderBookL2RequestV1::IsInitialized() const {
  return true;
}

void StreamOrderBookL2RequestV1::InternalSwap(StreamOrderBookL2RequestV1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.instrument_criteria_, other->_impl_.instrument_criteria_);
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamOrderBookL2RequestV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_getter, &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_once,
      file_level_metadata_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto[0]);
}

// ===================================================================

class StreamOrderBookL2ReplayRequestV1::_Internal {
 public:
  static const ::kaikosdk::InstrumentCriteria& instrument_criteria(const StreamOrderBookL2ReplayRequestV1* msg);
  static const ::kaikosdk::DataInterval& interval(const StreamOrderBookL2ReplayRequestV1* msg);
};

const ::kaikosdk::InstrumentCriteria&
StreamOrderBookL2ReplayRequestV1::_Internal::instrument_criteria(const StreamOrderBookL2ReplayRequestV1* msg) {
  return *msg->_impl_.instrument_criteria_;
}
const ::kaikosdk::DataInterval&
StreamOrderBookL2ReplayRequestV1::_Internal::interval(const StreamOrderBookL2ReplayRequestV1* msg) {
  return *msg->_impl_.interval_;
}
void StreamOrderBookL2ReplayRequestV1::clear_instrument_criteria() {
  if (GetArenaForAllocation() == nullptr && _impl_.instrument_criteria_ != nullptr) {
    delete _impl_.instrument_criteria_;
  }
  _impl_.instrument_criteria_ = nullptr;
}
void StreamOrderBookL2ReplayRequestV1::clear_interval() {
  if (GetArenaForAllocation() == nullptr && _impl_.interval_ != nullptr) {
    delete _impl_.interval_;
  }
  _impl_.interval_ = nullptr;
}
StreamOrderBookL2ReplayRequestV1::StreamOrderBookL2ReplayRequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamOrderBookL2ReplayRequestV1)
}
StreamOrderBookL2ReplayRequestV1::StreamOrderBookL2ReplayRequestV1(const StreamOrderBookL2ReplayRequestV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamOrderBookL2ReplayRequestV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_criteria_){nullptr}
    , decltype(_impl_.interval_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_instrument_criteria()) {
    _this->_impl_.instrument_criteria_ = new ::kaikosdk::InstrumentCriteria(*from._impl_.instrument_criteria_);
  }
  if (from._internal_has_interval()) {
    _this->_impl_.interval_ = new ::kaikosdk::DataInterval(*from._impl_.interval_);
  }
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamOrderBookL2ReplayRequestV1)
}

inline void StreamOrderBookL2ReplayRequestV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.instrument_criteria_){nullptr}
    , decltype(_impl_.interval_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StreamOrderBookL2ReplayRequestV1::~StreamOrderBookL2ReplayRequestV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamOrderBookL2ReplayRequestV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.instrument_criteria_;
  if (this != internal_default_instance()) delete _impl_.interval_;
}

void StreamOrderBookL2ReplayRequestV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamOrderBookL2ReplayRequestV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.instrument_criteria_ != nullptr) {
    delete _impl_.instrument_criteria_;
  }
  _impl_.instrument_criteria_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.interval_ != nullptr) {
    delete _impl_.interval_;
  }
  _impl_.interval_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamOrderBookL2ReplayRequestV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_instrument_criteria(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .kaikosdk.DataInterval interval = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_interval(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamOrderBookL2ReplayRequestV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::instrument_criteria(this),
        _Internal::instrument_criteria(this).GetCachedSize(), target, stream);
  }

  // .kaikosdk.DataInterval interval = 2;
  if (this->_internal_has_interval()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::interval(this),
        _Internal::interval(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  return target;
}

size_t StreamOrderBookL2ReplayRequestV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .kaikosdk.InstrumentCriteria instrument_criteria = 1;
  if (this->_internal_has_instrument_criteria()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.instrument_criteria_);
  }

  // .kaikosdk.DataInterval interval = 2;
  if (this->_internal_has_interval()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.interval_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamOrderBookL2ReplayRequestV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamOrderBookL2ReplayRequestV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamOrderBookL2ReplayRequestV1::GetClassData() const { return &_class_data_; }


void StreamOrderBookL2ReplayRequestV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamOrderBookL2ReplayRequestV1*>(&to_msg);
  auto& from = static_cast<const StreamOrderBookL2ReplayRequestV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_instrument_criteria()) {
    _this->_internal_mutable_instrument_criteria()->::kaikosdk::InstrumentCriteria::MergeFrom(
        from._internal_instrument_criteria());
  }
  if (from._internal_has_interval()) {
    _this->_internal_mutable_interval()->::kaikosdk::DataInterval::MergeFrom(
        from._internal_interval());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamOrderBookL2ReplayRequestV1::CopyFrom(const StreamOrderBookL2ReplayRequestV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamOrderBookL2ReplayRequestV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamOrderBookL2ReplayRequestV1::IsInitialized() const {
  return true;
}

void StreamOrderBookL2ReplayRequestV1::InternalSwap(StreamOrderBookL2ReplayRequestV1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StreamOrderBookL2ReplayRequestV1, _impl_.interval_)
      + sizeof(StreamOrderBookL2ReplayRequestV1::_impl_.interval_)
      - PROTOBUF_FIELD_OFFSET(StreamOrderBookL2ReplayRequestV1, _impl_.instrument_criteria_)>(
          reinterpret_cast<char*>(&_impl_.instrument_criteria_),
          reinterpret_cast<char*>(&other->_impl_.instrument_criteria_));
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamOrderBookL2ReplayRequestV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_getter, &descriptor_table_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto_once,
      file_level_metadata_sdk_2fstream_2forderbookl2_5fv1_2frequest_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamOrderBookL2RequestV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamOrderBookL2RequestV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamOrderBookL2RequestV1 >(arena);
}
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamOrderBookL2ReplayRequestV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamOrderBookL2ReplayRequestV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamOrderBookL2ReplayRequestV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
