// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/iv_svi_parameters_v1/request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sdk/core/assets.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto;
namespace kaikosdk {
class StreamIvSviParametersRequestV1;
struct StreamIvSviParametersRequestV1DefaultTypeInternal;
extern StreamIvSviParametersRequestV1DefaultTypeInternal _StreamIvSviParametersRequestV1_default_instance_;
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> ::kaikosdk::StreamIvSviParametersRequestV1* Arena::CreateMaybeMessage<::kaikosdk::StreamIvSviParametersRequestV1>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace kaikosdk {

// ===================================================================

class StreamIvSviParametersRequestV1 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kaikosdk.StreamIvSviParametersRequestV1) */ {
 public:
  inline StreamIvSviParametersRequestV1() : StreamIvSviParametersRequestV1(nullptr) {}
  ~StreamIvSviParametersRequestV1() override;
  explicit PROTOBUF_CONSTEXPR StreamIvSviParametersRequestV1(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamIvSviParametersRequestV1(const StreamIvSviParametersRequestV1& from);
  StreamIvSviParametersRequestV1(StreamIvSviParametersRequestV1&& from) noexcept
    : StreamIvSviParametersRequestV1() {
    *this = ::std::move(from);
  }

  inline StreamIvSviParametersRequestV1& operator=(const StreamIvSviParametersRequestV1& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamIvSviParametersRequestV1& operator=(StreamIvSviParametersRequestV1&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamIvSviParametersRequestV1& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamIvSviParametersRequestV1* internal_default_instance() {
    return reinterpret_cast<const StreamIvSviParametersRequestV1*>(
               &_StreamIvSviParametersRequestV1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(StreamIvSviParametersRequestV1& a, StreamIvSviParametersRequestV1& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamIvSviParametersRequestV1* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamIvSviParametersRequestV1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamIvSviParametersRequestV1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamIvSviParametersRequestV1>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamIvSviParametersRequestV1& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamIvSviParametersRequestV1& from) {
    StreamIvSviParametersRequestV1::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamIvSviParametersRequestV1* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kaikosdk.StreamIvSviParametersRequestV1";
  }
  protected:
  explicit StreamIvSviParametersRequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExchangesFieldNumber = 2,
    kAssetsFieldNumber = 1,
  };
  // string exchanges = 2;
  void clear_exchanges();
  const std::string& exchanges() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_exchanges(ArgT0&& arg0, ArgT... args);
  std::string* mutable_exchanges();
  PROTOBUF_NODISCARD std::string* release_exchanges();
  void set_allocated_exchanges(std::string* exchanges);
  private:
  const std::string& _internal_exchanges() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_exchanges(const std::string& value);
  std::string* _internal_mutable_exchanges();
  public:

  // .kaikosdk.Assets assets = 1;
  bool has_assets() const;
  private:
  bool _internal_has_assets() const;
  public:
  void clear_assets();
  const ::kaikosdk::Assets& assets() const;
  PROTOBUF_NODISCARD ::kaikosdk::Assets* release_assets();
  ::kaikosdk::Assets* mutable_assets();
  void set_allocated_assets(::kaikosdk::Assets* assets);
  private:
  const ::kaikosdk::Assets& _internal_assets() const;
  ::kaikosdk::Assets* _internal_mutable_assets();
  public:
  void unsafe_arena_set_allocated_assets(
      ::kaikosdk::Assets* assets);
  ::kaikosdk::Assets* unsafe_arena_release_assets();

  // @@protoc_insertion_point(class_scope:kaikosdk.StreamIvSviParametersRequestV1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr exchanges_;
    ::kaikosdk::Assets* assets_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StreamIvSviParametersRequestV1

// .kaikosdk.Assets assets = 1;
inline bool StreamIvSviParametersRequestV1::_internal_has_assets() const {
  return this != internal_default_instance() && _impl_.assets_ != nullptr;
}
inline bool StreamIvSviParametersRequestV1::has_assets() const {
  return _internal_has_assets();
}
inline const ::kaikosdk::Assets& StreamIvSviParametersRequestV1::_internal_assets() const {
  const ::kaikosdk::Assets* p = _impl_.assets_;
  return p != nullptr ? *p : reinterpret_cast<const ::kaikosdk::Assets&>(
      ::kaikosdk::_Assets_default_instance_);
}
inline const ::kaikosdk::Assets& StreamIvSviParametersRequestV1::assets() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamIvSviParametersRequestV1.assets)
  return _internal_assets();
}
inline void StreamIvSviParametersRequestV1::unsafe_arena_set_allocated_assets(
    ::kaikosdk::Assets* assets) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.assets_);
  }
  _impl_.assets_ = assets;
  if (assets) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kaikosdk.StreamIvSviParametersRequestV1.assets)
}
inline ::kaikosdk::Assets* StreamIvSviParametersRequestV1::release_assets() {
  
  ::kaikosdk::Assets* temp = _impl_.assets_;
  _impl_.assets_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::kaikosdk::Assets* StreamIvSviParametersRequestV1::unsafe_arena_release_assets() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamIvSviParametersRequestV1.assets)
  
  ::kaikosdk::Assets* temp = _impl_.assets_;
  _impl_.assets_ = nullptr;
  return temp;
}
inline ::kaikosdk::Assets* StreamIvSviParametersRequestV1::_internal_mutable_assets() {
  
  if (_impl_.assets_ == nullptr) {
    auto* p = CreateMaybeMessage<::kaikosdk::Assets>(GetArenaForAllocation());
    _impl_.assets_ = p;
  }
  return _impl_.assets_;
}
inline ::kaikosdk::Assets* StreamIvSviParametersRequestV1::mutable_assets() {
  ::kaikosdk::Assets* _msg = _internal_mutable_assets();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamIvSviParametersRequestV1.assets)
  return _msg;
}
inline void StreamIvSviParametersRequestV1::set_allocated_assets(::kaikosdk::Assets* assets) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.assets_);
  }
  if (assets) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(assets));
    if (message_arena != submessage_arena) {
      assets = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, assets, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.assets_ = assets;
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamIvSviParametersRequestV1.assets)
}

// string exchanges = 2;
inline void StreamIvSviParametersRequestV1::clear_exchanges() {
  _impl_.exchanges_.ClearToEmpty();
}
inline const std::string& StreamIvSviParametersRequestV1::exchanges() const {
  // @@protoc_insertion_point(field_get:kaikosdk.StreamIvSviParametersRequestV1.exchanges)
  return _internal_exchanges();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamIvSviParametersRequestV1::set_exchanges(ArgT0&& arg0, ArgT... args) {
 
 _impl_.exchanges_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:kaikosdk.StreamIvSviParametersRequestV1.exchanges)
}
inline std::string* StreamIvSviParametersRequestV1::mutable_exchanges() {
  std::string* _s = _internal_mutable_exchanges();
  // @@protoc_insertion_point(field_mutable:kaikosdk.StreamIvSviParametersRequestV1.exchanges)
  return _s;
}
inline const std::string& StreamIvSviParametersRequestV1::_internal_exchanges() const {
  return _impl_.exchanges_.Get();
}
inline void StreamIvSviParametersRequestV1::_internal_set_exchanges(const std::string& value) {
  
  _impl_.exchanges_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamIvSviParametersRequestV1::_internal_mutable_exchanges() {
  
  return _impl_.exchanges_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamIvSviParametersRequestV1::release_exchanges() {
  // @@protoc_insertion_point(field_release:kaikosdk.StreamIvSviParametersRequestV1.exchanges)
  return _impl_.exchanges_.Release();
}
inline void StreamIvSviParametersRequestV1::set_allocated_exchanges(std::string* exchanges) {
  if (exchanges != nullptr) {
    
  } else {
    
  }
  _impl_.exchanges_.SetAllocated(exchanges, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.exchanges_.IsDefault()) {
    _impl_.exchanges_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:kaikosdk.StreamIvSviParametersRequestV1.exchanges)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace kaikosdk

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sdk_2fstream_2fiv_5fsvi_5fparameters_5fv1_2frequest_2eproto
