// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sdk/stream/aggregated_state_price_v1/request.proto

#include "sdk/stream/aggregated_state_price_v1/request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace kaikosdk {
PROTOBUF_CONSTEXPR StreamAggregatedStatePriceRequestV1::StreamAggregatedStatePriceRequestV1(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.assets_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StreamAggregatedStatePriceRequestV1DefaultTypeInternal {
  PROTOBUF_CONSTEXPR StreamAggregatedStatePriceRequestV1DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StreamAggregatedStatePriceRequestV1DefaultTypeInternal() {}
  union {
    StreamAggregatedStatePriceRequestV1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StreamAggregatedStatePriceRequestV1DefaultTypeInternal _StreamAggregatedStatePriceRequestV1_default_instance_;
}  // namespace kaikosdk
static ::_pb::Metadata file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto = nullptr;

const uint32_t TableStruct_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceRequestV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::kaikosdk::StreamAggregatedStatePriceRequestV1, _impl_.assets_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::kaikosdk::StreamAggregatedStatePriceRequestV1)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::kaikosdk::_StreamAggregatedStatePriceRequestV1_default_instance_._instance,
};

const char descriptor_table_protodef_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n2sdk/stream/aggregated_state_price_v1/r"
  "equest.proto\022\010kaikosdk\"5\n#StreamAggregat"
  "edStatePriceRequestV1\022\016\n\006assets\030\001 \003(\tB\271\001"
  "\n.com.kaiko.sdk.stream.aggregated_state_"
  "price_v1P\001Z\\github.com/kaikodata/kaiko-g"
  "o-sdk/stream/aggregated_state_price_v1;a"
  "ggregated_state_price_v1\252\002&KaikoSdk.Stre"
  "am.AggregatedStatePriceV1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto = {
    false, false, 313, descriptor_table_protodef_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto,
    "sdk/stream/aggregated_state_price_v1/request.proto",
    &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto::offsets,
    file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto, file_level_enum_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto,
    file_level_service_descriptors_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto_getter() {
  return &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto(&descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto);
namespace kaikosdk {

// ===================================================================

class StreamAggregatedStatePriceRequestV1::_Internal {
 public:
};

StreamAggregatedStatePriceRequestV1::StreamAggregatedStatePriceRequestV1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:kaikosdk.StreamAggregatedStatePriceRequestV1)
}
StreamAggregatedStatePriceRequestV1::StreamAggregatedStatePriceRequestV1(const StreamAggregatedStatePriceRequestV1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StreamAggregatedStatePriceRequestV1* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.assets_){from._impl_.assets_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:kaikosdk.StreamAggregatedStatePriceRequestV1)
}

inline void StreamAggregatedStatePriceRequestV1::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.assets_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StreamAggregatedStatePriceRequestV1::~StreamAggregatedStatePriceRequestV1() {
  // @@protoc_insertion_point(destructor:kaikosdk.StreamAggregatedStatePriceRequestV1)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StreamAggregatedStatePriceRequestV1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.assets_.~RepeatedPtrField();
}

void StreamAggregatedStatePriceRequestV1::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StreamAggregatedStatePriceRequestV1::Clear() {
// @@protoc_insertion_point(message_clear_start:kaikosdk.StreamAggregatedStatePriceRequestV1)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.assets_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StreamAggregatedStatePriceRequestV1::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string assets = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_assets();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "kaikosdk.StreamAggregatedStatePriceRequestV1.assets"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StreamAggregatedStatePriceRequestV1::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kaikosdk.StreamAggregatedStatePriceRequestV1)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string assets = 1;
  for (int i = 0, n = this->_internal_assets_size(); i < n; i++) {
    const auto& s = this->_internal_assets(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "kaikosdk.StreamAggregatedStatePriceRequestV1.assets");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kaikosdk.StreamAggregatedStatePriceRequestV1)
  return target;
}

size_t StreamAggregatedStatePriceRequestV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kaikosdk.StreamAggregatedStatePriceRequestV1)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string assets = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.assets_.size());
  for (int i = 0, n = _impl_.assets_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.assets_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StreamAggregatedStatePriceRequestV1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StreamAggregatedStatePriceRequestV1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StreamAggregatedStatePriceRequestV1::GetClassData() const { return &_class_data_; }


void StreamAggregatedStatePriceRequestV1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StreamAggregatedStatePriceRequestV1*>(&to_msg);
  auto& from = static_cast<const StreamAggregatedStatePriceRequestV1&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kaikosdk.StreamAggregatedStatePriceRequestV1)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.assets_.MergeFrom(from._impl_.assets_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StreamAggregatedStatePriceRequestV1::CopyFrom(const StreamAggregatedStatePriceRequestV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kaikosdk.StreamAggregatedStatePriceRequestV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StreamAggregatedStatePriceRequestV1::IsInitialized() const {
  return true;
}

void StreamAggregatedStatePriceRequestV1::InternalSwap(StreamAggregatedStatePriceRequestV1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.assets_.InternalSwap(&other->_impl_.assets_);
}

::PROTOBUF_NAMESPACE_ID::Metadata StreamAggregatedStatePriceRequestV1::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto_getter, &descriptor_table_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto_once,
      file_level_metadata_sdk_2fstream_2faggregated_5fstate_5fprice_5fv1_2frequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace kaikosdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::kaikosdk::StreamAggregatedStatePriceRequestV1*
Arena::CreateMaybeMessage< ::kaikosdk::StreamAggregatedStatePriceRequestV1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::kaikosdk::StreamAggregatedStatePriceRequestV1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
